const manifest = {
  "id": "arabic_1",
  "author": "felixl@rambler.ru",
  "version": "2.7.2",
  "metadata": {
    "title": "Arabic Basics",
    "description": "First 200 words and building basic sentences",
    "level": "A0",
    "prerequisites": ["Alphabet"],
    "goals": ["Basic Greetings", "Simple Sentences"]
  },
  "target_language": "ar",
  "feedback": {
    "perfect": [
      ["Great!", "أَحْسَنْتَ!", "Aḥsanta!"],
      ["Perfect!", "مُمْتَاز!", "Mumtāz!"],
      ["Mashallah!", "مَا شَاءَ الله!", "Mā shā'a Allāh!"]
    ],
    "good": [
      ["Good job!", "عَمَلٌ جَيِّد!", "'Amalun jayyid!"],
      ["Well done!", "بَطَل!", "Baṭal!"]
    ],
    "tryAgain": [
      ["Try again", "حَاوِلْ مَرَّةً أُخْرَى", "Ḥāwil marratan ukhrā"],
      ["Don't give up!", "لَا تَسْتَسْلِم!", "Lā tastaslim!"]
    ]
  },
  "course_locales":
  {
    "en": {
      "__title__": "English",
      "__dir__": "ltr",
    },
    "ru": {
      "__title__": "Русский",
      "__dir__": "ltr",
      "Arabic Basics": "Основы арабского",
      "First 200 words and building basic sentences": "Первые 200 слов и базовые конструкции предложения.",
      "Great!": "Отлично!",
      "Perfect!": "Превосходно!",
      "Mashallah!": "Машалла!",
      "Good job!": "Хорошая работа!",
      "Well done!": "Молодец!",
      "Try again": "Попробуй еще раз",
      "Don't give up!": "Не сдавайся!",
      "All topics": "Все темы",
      "Tell about yourself 1": "Рассказ о себе 1",
      "Professions and studies 1": "Профессии и учёба 1",
      "Everyday life 1": "Быт и обиход 1",
      "Hobbies and travel 1": "Хобби и путешествия 1",
      "Restaurant 1": "Ресторан 1",
      "Airport 1": "Аэропорт 1",
      "Names meaning 1": "Значения имён 1",
      "Polite language 1": "Вежливые обращения 1",
  "nice to meet you": "приятно познакомиться",
  "name": "имя",
  "profession": "профессия",
  "programmer": "программист",
  "engineer": "инженер",
  "developer": "разработчик",
  "company": "компания",
  "family": "семья",
  "father": "отец",
  "mother": "мать",
  "brother": "брат",
  "sister": "сестра",
  "house": "дом",
  "mr.": "господин",
  "mrs.": "госпожа",
  "miss": "девушка",
  "city": "город",
  "country / town": "страна / город",
  "to live": "жить",
  "to work": "работать",
  "congrats!": "поздравляю!",
  "ok": "хорошо",
  "sorry": "извини",
  "exactly": "совершенно верно",
  "thanks": "спасибо",
  "to study": "учиться",
  "now": "сейчас",
  "with": "с",
  "in": "в / внутри",
  "i work as a programmer": "я работаю программистом",
  "i work remotely": "я работаю удалённо",
  "i live in a big city": "я живу в большом городе",
  "i have a small family": "у меня небольшая семья",
  "my father is an engineer": "мой отец инженер",
  "my mother is a teacher": "моя мать учительница",
  "beautiful house": "красивый дом",
  "beautiful new house": "красивый новый дом",
  "i have a brother and a sister": "у меня есть брат и сестра",
  "i work in an international company": "я работаю в международной компании",
  "where are you from?": "откуда ты?",
  "i am from russia": "я из россии",
  "i don't understand": "я не понимаю",
  "once more please": "ещё раз пожалуйста",
  "where do you live?": "где ты живешь",
  "what is your profession?": "какая твоя профессия",
  "i study arabic now": "я учу арабский язык сейчас",
  "my house is here": "мой дом здесь",
  "i love my job": "я люблю свою работу",
  "we live together": "мы живем вместе",
  "tailor": "портная",
  "mathematician": "математик",
  "teacher": "учитель",
  "designer": "дизайнер",
  "workshop": "мастерская",
  "art": "искусство",
  "academy": "академия",
  "student": "студентка",
  "cinema": "кинематография",
  "faculty / college": "факультет",
  "university": "университет",
  "lesson": "урок",
  "science": "наука",
  "blueprint / drawing": "чертеж",
  "fabric": "ткань",
  "numbers": "цифры",
  "project": "проект",
  "exam": "экзамен",
  "library": "библиотека",
  "she works as a tailor in the workshop": "она работает портной в мастерской",
  "the student studies at the faculty of arts": "студентка учится на факультете искусств",
  "the mathematician works in the academy": "математик работает в академии",
  "the designer is making a project in the studio": "дизайнер создает проект в студии",
  "the teacher explains the lesson in class": "учитель объясняет урок в классе",
  "i love cinema and art": "я люблю кинематограф и искусство",
  "she is sewing a dress from beautiful fabric": "она шьет платье из красивой ткани",
  "we study math at the university": "мы изучаем математику в университете",
  "this workshop is very big": "эта мастерская очень большая",
  "the student has an exam tomorrow": "у студентки завтра экзамен",
  "the math professor writes numbers": "профессор математики пишет цифры",
  "the academy is open for students": "академия открыта для студентов",
  "the designer works on a new blueprint": "дизайнер работает над новым чертежом",
  "the art lesson starts now": "урок искусства начинается сейчас",
  "carpet": "ковёр",
  "bed": "кровать",
  "wardrobe / closet": "шкаф",
  "room": "комната",
  "kitchen": "кухня",
  "bedroom": "спальня",
  "window": "окно",
  "floor": "пол",
  "ceiling": "потолок",
  "kettle": "чайник",
  "glass / cup": "стакан",
  "plate": "тарелка",
  "knife": "нож",
  "fork": "вилка",
  "spoon": "ложка",
  "oven / stove": "печка",
  "tap / sink": "кран / раковина",
  "the carpet is on the floor": "ковёр лежит на полу",
  "the wardrobe is in the room": "шкаф стоит в комнате",
  "the bed is big and comfortable": "кровать большая и удобная",
  "this bedroom is very bright": "эта спальня очень светлая",
  "the kitchen window is open": "окно в кухне открыто",
  "the ceiling is white and high": "потолок белый и высокий",
  "the kettle is on the stove now": "чайник сейчас на печке",
  "the glass is on the table": "стакан стоит на столе",
  "the spoon and fork are here": "ложка и вилка здесь",
  "the knife and plate are clean": "нож и тарелка чистые",
  "the tap is in the kitchen": "кран в кухне",
  "i am going to the bedroom": "я иду в спальню",
  "there is a window in the room": "в комнате есть окно",
  "where is my knife": "где лежит мой нож",
  "the kettle is hot": "чайник горячий",
  "renting": "аренда",
  "inside the country": "внутри страны",
  "abroad": "за рубеж",
  "here": "здесь",
  "studying": "изучение",
  "culture": "культура",
  "better": "лучше",
  "car": "машина",
  "music": "музыка",
  "people / nation": "народ",
  "public transport": "общественный транспорт",
  "trip / flight": "поездка",
  "travel": "путешествие",
  "watching": "просмотр",
  "visiting / visit": "посещение",
  "free time": "свободное время",
  "there": "там",
  "transport": "транспорт",
  "tourism": "туризм",
  "movies": "фильмы",
  "languages": "языки",
  "my family loves traveling": "моя семья любит путешествовать",
  "traveling abroad is fun": "путешествие за рубеж интересно",
  "public transport here is better": "здесь общественный транспорт лучше",
  "this city is very beautiful": "этот город очень красивый",
  "the car here is better": "машина здесь лучше",
  "i like listening to music": "люблю слушать музыку",
  "i watch movies sometimes": "смотрю фильмы иногда",
  "i study different languages": "изучаю разные языки",
  "we study different cultures": "изучаем разные культуры",
  "we love local tourism": "любим местный туризм",
  "we rent a car there": "арендуем машину там",
  "we visited european countries": "посетили страны Европы",
  "i love this city": "люблю этот город",
  "we get to know nations": "знакомимся с народами",
  "i am going to the city center": "еду в центр",
  "tasty / delicious": "вкусный",
  "salty": "солёный",
  "sweet": "сладкий",
  "sour": "кислый",
  "hot": "горячий",
  "cold": "холодный",
  "appetizer / meze": "закуска",
  "main course": "основное блюдо",
  "side dish": "гарнир",
  "dessert": "десерт",
  "the bill / check": "счёт",
  "meat": "мясо",
  "rice": "рис",
  "i want": "хочу",
  "cup": "чашка",
  "almonds": "миндаль",
  "almond milk": "миндальное молоко",
  "no sugar": "без сахара",
  "substitute / alternative": "заменитель",
  "i like / love": "люблю",
  "i want a main course": "хочу основное блюдо",
  "i like meat with rice": "люблю мясо с рисом",
  "the appetizer is very salty": "закуска очень солёная",
  "the dessert is too sweet": "десерт слишком сладкий",
  "the lemon is very sour": "лимон очень кислый",
  "the tea is hot now": "чай сейчас горячий",
  "the water here is cold": "вода здесь холодная",
  "the side dish is very tasty": "гарнир очень вкусный",
  "bring the bill please": "принеси счёт пожалуйста",
  "where is the dessert?": "где десерт",
  "the meal is very tasty": "блюдо очень вкусное",
  "i want cold juice": "хочу холодный сок",
  "the rice is very salty": "рис очень солёный",
  "i want this dessert": "хочу этот десерт",
  "the restaurant is very tasty": "ресторан очень вкусный",
  "i want strong coffee": "хочу крепкий кофе",
  "i want almond milk": "хочу миндальное молоко",
  "coffee without sugar": "кофе без сахара",
  "give me a cup": "дай мне чашку",
  "this coffee is strong": "этот кофе крепкий",
  "i want a milk substitute": "хочу заменитель молока",
  "this cup is hot": "эта чашка горячая",
  "airport": "аэропорт",
  "airplane": "самолёт",
  "flight / trip": "рейс / полёт",
  "ticket": "билет / талон",
  "passport": "паспорт",
  "baggage / luggage": "багаж",
  "suitcase / bag": "чемодан",
  "hand luggage": "ручная кладь",
  "inspection / search": "контроль / досмотр",
  "security": "безопасность",
  "layover / transit": "пересадка",
  "seat": "место",
  "free / empty": "свободно",
  "occupied / reserved": "занято",
  "border": "граница",
  "visit": "визит",
  "hotel": "гостиница",
  "purpose / goal": "цель",
  "where is my passport?": "где мой паспорт",
  "the flight is delayed now": "рейс сейчас задерживается",
  "the airplane is very big": "самолёт очень большой",
  "i want a seat by the window": "хочу место у окна",
  "is this seat free?": "это место свободно",
  "no, this seat is occupied": "нет это место занято",
  "where is the security check?": "где досмотр безопасности",
  "the suitcase is very heavy": "чемодан очень тяжелый",
  "this is my hand luggage": "это моя ручная кладь",
  "i have a layover": "у меня есть пересадка",
  "where is the boarding pass?": "где посадочный талон",
  "the luggage is there below": "багаж там внизу",
  "border control is here": "пограничный контроль здесь",
  "i want to change the seat": "хочу поменять место",
  "the purpose of the visit is tourism": "цель визита туризм",
  "the hotel is in the city center": "гостиница в центре города",
  "the airport is very beautiful": "аэропорт очень красивый",
  "happy (m)": "счастливый",
  "beautiful (m)": "красивый",
  "kind / good (m)": "добрый / хороший",
  "tall / high (m)": "высокий",
  "calm / quiet (m)": "спокойный",
  "generous (m)": "щедрый",
  "loyal / faithful (m)": "верный",
  "smart / understanding (m)": "умный",
  "man / guy": "человек / мужчина",
  "employee (m)": "сотрудник / работник",
  "bright / shining (m)": "яркий / светлый",
  "strong / tough (m)": "крепкий / сильный",
  "flower": "цветок",
  "rose": "роза",
  "star": "звезда",
  "light / glow": "свет / сияние",
  "sun": "солнце",
  "clear / pure (f)": "ясная / чистая",
  "moon": "луна",
  "pearl": "жемчужина",
  "generous (f)": "щедрая",
  "beautiful (f)": "красивая",
  "happy (f)": "счастливая",
  "kind / good (f)": "добрая",
  "this man is very happy": "этот человек очень счастливый",
  "your friend is very handsome": "твой друг очень красивый",
  "my brother is very kind": "мой брат очень добрый",
  "this boy is very tall": "этот парень очень высокий",
  "the sea is very calm today": "море сегодня очень спокойное",
  "your father is very generous": "твой отец очень щедрый",
  "this employee is very loyal": "этот сотрудник очень верный",
  "my son is very smart": "мой сын очень умный",
  "this man is very kind": "этот человек очень добрый",
  "your voice is very bright": "твой голос очень яркий",
  "this coffee is very strong": "этот кофе очень крепкий",
  "our neighbor is very calm": "наш сосед очень спокойный",
  "this flower is very beautiful": "этот цветок очень красивый",
  "the sun is very hot today": "сегодня солнце очень горячее",
  "this star is very bright": "эта звезда очень яркая",
  "your room is very bright": "твоя комната очень светлая",
  "this rose is very beautiful": "эта роза очень красивая",
  "the sky is very clear today": "небо сегодня очень чистое",
  "your sister is very happy": "твоя сестра очень счастливая",
  "my mom is very kind": "моя мама очень добрая",
  "the moon is very beautiful today": "луна сегодня очень красивая",
  "this woman is very generous": "эта женщина очень щедрая",
  "thank god": "слава богу",
  "god forbid": "не дай бог",
  "to your health (cheers)": "на здоровье",
  "bon appetit": "приятного аппетита",
  "be careful / watch out": "осторожно",
  "please / you are welcome": "пожалуйста",
  "be so kind / please": "будьте добры",
  "unfortunately i can't": "к сожалению не могу",
  "i wish you luck": "желаю удачи",
  "welcome": "добро пожаловать",
  "make yourself at home": "располагайтесь",
  "have a safe trip": "счастливого пути",
  "don't worry / no need to worry": "не стоит беспокоиться",
  "please / go ahead / take it": "пожалуйста (приглашение)",
  "it's my pleasure": "не за что / мне в радость",
  "it doesn't matter / never mind": "неважно / пустяки",
  "congratulations": "поздравляю",
  "thanks (reply to mabruk)": "спасибо (в ответ на поздравление)",
  "everything is good, thank god": "всё хорошо, слава богу",
  "bon appetit to everyone": "приятного аппетита всем",
  "be careful on the road": "осторожно на дороге",
  "please, i want a menu": "будьте добры, я хочу меню",
  "nice to meet you, my friend": "приятно познакомиться, мой друг",
  "unfortunately i can't come today": "к сожалению не могу прийти сегодня",
  "i wish you luck in work": "желаю тебе удачи в работе",
  "no, god forbid": "нет, не дай бог",
  "welcome to our house": "добро пожаловать в наш дом",
  "make yourself at home, my friend": "располагайтесь, мой друг",
  "have a safe trip to russia": "счастливого пути в Россию",
  "don't worry about the money": "не стоит беспокоиться о деньгах",
  "please, sit here": "пожалуйста, садись здесь",
  "it's not a problem, never mind": "это не проблема, неважно",
  "congratulations on the new job": "поздравляю с новой работой",
  "it's my pleasure, no need to thank": "не стоит благодарности, мне в радость"
    }
  }
}
